apiVersion: v2
name: meshapps
description: Umbrella-repository of apps supported by the IOP and its adapters
type: application
version: 0.0.3
appVersion: 0.0.1
dependencies:
- name: collabora-code
  version: 2.0.0
  repository: "https://chrisingenhaag.github.io/helm/"
  condition: collabora-code.enabled
- name: codimd
  version: 0.1.8
  repository: "https://helm.codimd.dev/"
  condition: codimd.enabled
