gateway:
  enabled: true
  configFiles:
    revad.toml: |
      [grpc.services.gateway]
      datagateway = "iop-gateway/iop/datagateway"
      commit_share_to_storage_grant = true
      commit_share_to_storage_ref = true

      [grpc.services.storageregistry]
      [grpc.services.storageregistry.drivers.static]
      home_provider = "/home"

      [grpc.services.storageregistry.drivers.static.rules]
      "/home" = {"address" = "iop-storageprovider-home:17000"}
      "/reva" = {"address" = "iop-storageprovider-reva:18000"}
      "123e4567-e89b-12d3-a456-426655440000" = {"address" = "iop-storageprovider-reva:18000"}

      [grpc.services.authprovider]
      [grpc.services.authregistry]
      [grpc.services.userprovider]
      [grpc.services.usershareprovider]
      [grpc.services.groupprovider]
      [grpc.services.publicshareprovider]
      [grpc.services.ocmcore]
      [grpc.services.ocmshareprovider]
      [grpc.services.ocminvitemanager]
      [grpc.services.ocmproviderauthorizer]

      [http.services.datagateway]
      [http.services.ocmd]
      [http.services.ocdav]
      [http.services.ocs]

storageprovider-home:
  enabled: true
  service:
    grpc:
      port: 17000
    http:
      port: 17001
  configFiles:
    revad.toml: |
      [grpc]
      address = "0.0.0.0:17000"

      [grpc.services.storageprovider]
      driver = "localhome"
      mount_path = "/home"
      mount_id = "123e4567-e89b-12d3-a456-426655440000"
      data_server_url = "http://iop-storageprovider-home:17001/data"

      [http]
      address = "0.0.0.0:17001"

      [http.services.dataprovider]
      driver = "localhome"

storageprovider-reva:
  enabled: true
  service:
    grpc:
      port: 18000
    http:
      port: 18001
  configFiles:
    revad.toml: |
      [grpc]
      address = "0.0.0.0:18000"

      [grpc.services.storageprovider]
      driver = "local"
      mount_path = "/reva"
      mount_id = "123e4567-e89b-12d3-a456-426655440000"
      data_server_url = "http://iop-storageprovider-reva:18001/data"

      [http]
      address = "0.0.0.0:18001"

      [http.services.dataprovider]
      driver = "local"

wopiserver:
  enabled: true
